
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports: 
      - "5002:5002"
    environment:
      - JWT_SECRET_KEY=aidwkprkqpdkw924314
      - BOT_CONTROL_URL=http://bot:8082
      - BASE_URL=http://backend:5002
      - STATIC_URL=http://localhost:5002
      - DEBUG=True
      - DOCKER=True
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./backend/static:/app/static
    command: ["/app/entrypoint.sh"]

  bot:
    build:
      context: ./BotCore
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8082:8082"
    environment:
      - API_URL=http://backend:5002/bot
      - DEBUG=True
      - DOCKER=True
      - PYTHONUNBUFFERED=1
    volumes:
      - ./BotCore/bot/plugins:/bot/bot/plugins

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_BACKEND_API_URL=http://localhost:5002
    ports:
      - "3002:3002"


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bot_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
