
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports: 
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=aidwkprkqpdkw924314
      - BOT_CONTROL_URL=http://bot:8081
      - BASE_URL=http://backend:5000
      - STATIC_URL=http://localhost:5000
      - DEBUG=True
      - DOCKER=True
    volumes:
      - ./backend/static:/app/static

  bot:
    build:
      context: ./BotCore
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8081:8081"
    environment:
      - API_URL=http://backend:5000/bot
      - DEBUG=True
      - DOCKER=True
      - PYTHONUNBUFFERED=1
    volumes:
      - ./BotCore/bot/plugins:/bot/bot/plugins

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bot_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 40
    ports:
      - "8080:80"


volumes:
  db_data:
